name: Test composite action

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: tlambert03/napari-plugin-action@main
      with:
        package_name: napari_svg
